[plugin]
name = "mc-rcon"
version = "1.0.0"
description = "Minecraft RCON control plugin"
authors = ["Vollate"]
license = "MIT"
homepage = "https://github.com/vollate/obcx-plugin-mc-rcon"

[dependencies]
required_plugins = []

[build]
vcpkg_deps = ["tomlplusplus"]
